# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/supports', type: :request do
  before(:each) do
    @current_user = create(:user)
    sign_in(@current_user)
  end

  let(:valid_attributes) do
    {
      subject: Faker::Name.name, email: Faker::Internet.email, description: Faker::String.random(length: 3..12),
      user_id: @current_user.id, company_id: @current_user.company_id
    }
  end

  let(:invalid_attributes) do
    { email: nil, description: nil }
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_support_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Support' do
        expect do
          post supports_url, params: { support: valid_attributes }
        end.to change(Support, :count).by(1)
      end

      it 'redirects to the created support' do
        post supports_url, params: { support: valid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Support' do
        expect do
          post supports_url, params: { support: invalid_attributes }
        end.to change(Support, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post supports_url, params: { support: invalid_attributes }
        expect(response).to render_template(:new)
      end
    end
  end
end
