require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_designations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserDesignation. As you add validations to UserDesignation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserDesignation.create! valid_attributes
      get user_designations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_designation = UserDesignation.create! valid_attributes
      get user_designation_url(user_designation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_designation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_designation = UserDesignation.create! valid_attributes
      get edit_user_designation_url(user_designation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserDesignation" do
        expect {
          post user_designations_url, params: { user_designation: valid_attributes }
        }.to change(UserDesignation, :count).by(1)
      end

      it "redirects to the created user_designation" do
        post user_designations_url, params: { user_designation: valid_attributes }
        expect(response).to redirect_to(user_designation_url(UserDesignation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserDesignation" do
        expect {
          post user_designations_url, params: { user_designation: invalid_attributes }
        }.to change(UserDesignation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_designations_url, params: { user_designation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_designation" do
        user_designation = UserDesignation.create! valid_attributes
        patch user_designation_url(user_designation), params: { user_designation: new_attributes }
        user_designation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_designation" do
        user_designation = UserDesignation.create! valid_attributes
        patch user_designation_url(user_designation), params: { user_designation: new_attributes }
        user_designation.reload
        expect(response).to redirect_to(user_designation_url(user_designation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_designation = UserDesignation.create! valid_attributes
        patch user_designation_url(user_designation), params: { user_designation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_designation" do
      user_designation = UserDesignation.create! valid_attributes
      expect {
        delete user_designation_url(user_designation)
      }.to change(UserDesignation, :count).by(-1)
    end

    it "redirects to the user_designations list" do
      user_designation = UserDesignation.create! valid_attributes
      delete user_designation_url(user_designation)
      expect(response).to redirect_to(user_designations_url)
    end
  end
end
